export const designTokens = {
  colors: {
    semantic: {
      bg: 'var(--color-bg)',
      'bg-subtle': 'var(--color-bg-subtle)',
      surface: 'var(--color-surface)',
      'surface-muted': 'var(--color-surface-muted)',
      'surface-elevated': 'var(--color-surface-elevated)',
      'surface-sunken': 'var(--color-surface-sunken)',
      text: 'var(--color-text)',
      'text-muted': 'var(--color-text-muted)',
      'text-subtle': 'var(--color-text-subtle)',
      'text-inverse': 'var(--color-text-inverse)',
      border: 'var(--color-border)',
      'border-strong': 'var(--color-border-strong)',
      'border-subtle': 'var(--color-border-subtle)',
      primary: 'var(--color-brand-500)',
      secondary: 'var(--color-brand-600)',
      success: 'var(--color-success)',
      warning: 'var(--color-warning)',
      danger: 'var(--color-danger)',
      info: 'var(--color-info)',
    },
    sentiment: {
      positive: 'var(--color-sentiment-positive)',
      neutral: 'var(--color-sentiment-neutral)',
      negative: 'var(--color-sentiment-negative)',
    },
  },
  typography: {
    fontFamily: {
      sans: 'var(--font-sans)',
      mono: 'var(--font-mono)',
    },
    fontSize: {
      xs: '0.75rem',
      sm: '0.875rem',
      base: '1rem',
      lg: '1.125rem',
      xl: '1.25rem',
      '2xl': '1.5rem',
      '3xl': '1.875rem',
      '4xl': '2.25rem',
    },
  },
  spacing: {
    0: '0px',
    1: '0.25rem',
    2: '0.5rem',
    3: '0.75rem',
    4: '1rem',
    5: '1.25rem',
    6: '1.5rem',
    7: '1.75rem',
    8: '2rem',
    9: '2.25rem',
    10: '2.5rem',
    11: '2.75rem',
    12: '3rem',
    14: '3.5rem',
    16: '4rem',
    20: '5rem',
    24: '6rem',
    28: '7rem',
    32: '8rem',
  },
  radius: {
    none: '0px',
    sm: '0.25rem',
    md: '0.375rem',
    lg: '0.5rem',
    xl: '0.75rem',
    '2xl': '1rem',
    '3xl': '1.5rem',
    full: '9999px',
  },
  shadows: {
    xs: 'var(--shadow-xs)',
    sm: 'var(--shadow-sm)',
    md: 'var(--shadow-md)',
    lg: 'var(--shadow-lg)',
    xl: 'var(--shadow-xl)',
    '2xl': 'var(--shadow-2xl)',
  },
  motion: {
    duration: {
      xs: '80ms',
      fast: '120ms',
      normal: '180ms',
      slow: '260ms',
    },
    easing: {
      standard: 'cubic-bezier(0.4, 0, 0.2, 1)',
      emphasize: 'cubic-bezier(0.16, 1, 0.3, 1)',
    },
  },
  icons: {
    xs: '12px',
    sm: '14px',
    md: '16px',
    lg: '20px',
    xl: '24px',
  },
  breakpoints: {
    sm: '640px',
    md: '768px',
    lg: '1024px',
    xl: '1280px',
    '2xl': '1536px',
  },
}
